[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = true
sslCertFile = ''
sslKeyFile = ''
maxUploadSize = 200
enableWebsocketCompression = true
runOnSave = true
allowRunOnSave = true

[browser]
serverAddress = "0.0.0.0"
serverPort = 8501
gatherUsageStats = false

[theme]
base = "dark"

[client]
showErrorDetails = true
toolbarMode = "auto"